[default]
log_level = 'INFO'
prob_of_execution = 1
max_transitions = 5
max_time = '23:59:01'
start_time = '18:00:00'
init_time = '00:00:05'
min_off_time = '30 minutes'
max_off_time = '60 minutes'
min_on_time = '20 minutes'
max_on_time = '90 minutes'
wemo_address = '192.168.4.6'
server_port = 8080
server_address = '0.0.0.0'
